Adding utility to create compliant science filenames
HERMES-SOC/hermes_core pull request #12
Opened 2022-06-24 16:00 UTC by ehsteve

This addresses issue #10 as well as issue #11.

2022-06-24 18:55 UTC, ehsteve commented
Looks like tests are failing only for Python 3.7 because of some issue with the `mock` module which `pytest` uses. Investigating the problem.

2022-06-27 18:18 UTC, acrager commented on hermes_core/util/util.py
> +        The data level. Must be one of the following
Need to finish your sentence here.:)

2022-06-28 00:50 UTC, ehsteve commented on hermes_core/util/util.py
> +        The time
Sorry. What does your comment mean? Not sure I understand.

2022-06-28 00:52 UTC, ehsteve commented
Thank you for your review @acrager but you need to be meaner! Hold approval to when testing passes ;)

2022-06-28 12:23 UTC, ehsteve commented
I am going to add to the scope of this merge request by also addressing issue #13 which is very related.

2022-07-06 21:23 UTC, swkre requested changes

2022-07-06 21:23 UTC, swkre commented on hermes_core/tests/test_util_util.py
> +            "eeb", "2023-13-04T12:06:21", level=good_level, version=good_version
```suggestion
            good_instrument, "2023-13-04T12:06:21", level=good_level, version=good_version
```

2022-07-06 21:23 UTC, swkre commented on hermes_core/tests/test_util_util.py
> +            "eeb", "2023-13-04T12:06:21", level=good_level, version=good_version
Fix on similar 'eeb' starting lines below

2022-07-11 16:12 UTC, ehsteve commented on hermes_core/util/util.py
> +        The data level. Must be one of the following
It has been

2022-07-11 16:12 UTC, ehsteve commented on hermes_core/util/util.py
> +    instrument, time: str, mode="", level="l0", version="", descriptor="", test=False
Done.

2022-07-13 22:33 UTC, acrager commented on hermes_core/util/util.py
> +        The time
I originally thought that "The time" was an unfinished sentence. Just ignore this comment.

2022-07-13 23:01 UTC, acrager approved these changes
All tests passed. Noted a little non-impacting typo in a test utility function name that might just be how Steve C. shortens "output", who knows.

2022-07-14 13:55 UTC, ehsteve commented on hermes_core/tests/test_util_util.py
> +def test_parse_science_filename_ouput():
Good catch! Thanks. Fixed it and added doc strings as you recommended.

2022-07-14 14:00 UTC, merged